import { cn } from "@/lib/utils";
import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  Bookmark,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  ClipboardList,
  DraftingCompass,
  Download,
  Eye,
  EyeOff,
  Factory,
  Flag,
  GraduationCap,
  Hammer,
  HelpCircle,
  Handshake,
  Image as ImageIcon,
  Info,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquareText,
  MapPin,
  Microscope,
  Paintbrush,
  Phone,
  Plus,
  Rss,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShoppingBag,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Sprout,
  Trash2,
  TrendingUp,
  UserCircle,
  UserPlus,
  UserSearch,
  Utensils,
  Video,
  X,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  account_balance: Scale,
  account_circle: UserCircle,
  add: Plus,
  architecture: DraftingCompass,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  assignment_late: ClipboardList,
  badge: BadgeCheck,
  balance: Scale,
  bell: Bell,
  biotech: Microscope,
  bookmark: Bookmark,
  business_center: BriefcaseBusiness,
  calendar_today: CalendarDays,
  call: Phone,
  campaign: Megaphone,
  chat: MessageCircle,
  chat_bubble: MessageCircle,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  construction: Hammer,
  delete: Trash2,
  design_services: Paintbrush,
  download: Download,
  eco: Sprout,
  error: CircleAlert,
  expand_more: ChevronDown,
  factory: Factory,
  flag: Flag,
  group_add: UserPlus,
  handshake: Handshake,
  help: HelpCircle,
  image: ImageIcon,
  info: Info,
  lightbulb: Lightbulb,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  notifications: Bell,
  progress_activity: LoaderCircle,
  psychology: Sparkles,
  public: Building2,
  rate_review: MessageSquareText,
  restaurant: Utensils,
  rss_feed: Rss,
  school: GraduationCap,
  search: Search,
  search_off: SearchX,
  send: Send,
  settings: Settings,
  shield: Shield,
  shopping_bag: ShoppingBag,
  sentiment_satisfied: Smile,
  spa: Leaf,
  space_dashboard: LayoutDashboard,
  dashboard: LayoutDashboard,
  person_search: UserSearch,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  verified: BadgeCheck,
  videocam: Video,
  visibility: Eye,
  visibility_off: EyeOff,
};

export function Icon({
  name,
  filled,
  className,
}: {
  name: string;
  filled?: boolean;
  className?: string;
}) {
  const Component = ICONS[name] ?? CircleAlert;
  const shouldFill = filled && name === "bookmark";
  return (
    <Component
      aria-hidden="true"
      className={cn("inline-block size-[1em] shrink-0 select-none", className)}
      fill={shouldFill ? "currentColor" : "none"}
      strokeWidth={filled ? 2.4 : 2}
    />
  );
}
